### ISSUE TITLE
Why CKB can't read the unix timestamp ?

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/rfcs#196]
Still confused me that why that ckb can't read the unix timestamp like bitcoin?
What does core team think about that ? Any drawback of UNIX timestamp?

**Comment by jjyr** [comment]
Can you give an example of how to read the unix timestamp in Bitcoin?

**Comment by doitian** [comment]
CKB does support reading the timestamp in header when it is referenced in header deps. If you want to read current timestamp, or the timestamp the transaction is packaged in, no, CKB does not allow it. A principle of transaction verification is that once all the cell deps and header deps are resolved, the verification result is determined, it should not depend on external environment, even which block this transaction is packaged.

**Comment by Rbchi** [comment]
Thanks for answering and giving me a chance to explain more about my confusion. What I want to check is could we use the external physical time on CKB. Sometimes like Oracle would need to get the price feed. As far as I know, Eth could do, and like Bitcion use UNIX timestamp to make sure the block sequence, and use MAX_FUTURE_BLOCK_TIME to prevent miners from sending problematic timestamp.

**Comment by jjyr** [comment]
As far as I know, in Bitcoin, you can indirectly control spending time of coins via [Timelock](https://en.bitcoin.it/wiki/Timelock). 

CKB provides a similar mechanism called [transaction valid since](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0017-tx-valid-since/0017-tx-valid-since.md); you can write a contract to control when a cell can be unlocked.

It's impossible to read external physical time directly(Please correct me if I'm wrong) in both Bitcoin and CKB.

**Comment by janx** [comment]
@jjyr also gave a reference here: [Off-chain determinism](https://talk.nervos.org/t/off-chain-determinism/5155)
